### ISSUE TITLE
v5.0 Changing model resets q range

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1325]
Once a model is plotted, changing the model will reset the q range option and the q resolution option.

If you select slit smearing, that option will be deselected. If you select it again, the value that was previously entered as 'slit height' now populates the 'slit width' box.

**Comment by rozyczko** [comment]
fixed the q resolution persistence and some incorrect parameter setup.

**Comment by rozyczko** [comment]
... and the q ranges got corrected as well.

**Comment by rozyczko** [comment]
Moving to 5.1.0 so Mathieu can review it later (was tested/reviewed locally).

**Comment by mdoucet** [comment]
I tried the latest build of the [SasView-OSX1013](https://jenkins.esss.dk/sasview-beta/job/SasView-OSX1013/576/). The q range option works, but the following doesn't:

- The choice of smearing type works, but the values for slit height and slit width are switched when using pinhole smearing and selecting a new model.

- After choosing a new model, if you click calculate and go back to the _Resolution_ tab, you'll see that the instrument smearing option is now _None_.

**Comment by rozyczko** [comment]
Both points have been addressed.

**Comment by rozyczko** [comment]
Please review whenever possible

**Comment by mdoucet** [comment]
I tried the latest build of [SasView-OSX1013](https://jenkins.esss.dk/sasview-beta/job/SasView-OSX1013/623/).

Most of the problems are fixed, but I still get this issue:

- Load a data set
- Pick a model
- On the resolution tab, pick custom slit smearing
- Fill the **Slit Height** to 0.1
- Go back to the model tab and pick another model
- Go back to the resolution tab, and you'll see that the **Slit Width** is now 0.1 and **Slit Height** is 0.

**Comment by rozyczko** [comment]
Good catch. Fixed in ESS_GUI.

**Comment by rozyczko** [comment]
Reviewed locally. Closing.
