### ISSUE TITLE
5.0 corfunc mac doesn't plot

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1339]
Going through the correlation function documentation (SasView 4.2.2 since dmg for mac doesn't provide 5.0 docs), I see the following:
* Name of the dataset is not appearing in the Name box.
* Range bars on graph are not draggable.
* Input dialog not scrollable (but I can access the buttons on the bottom by closing the log explorer)
* sigma value is slightly different (5.8e-10 rather than 7.7e-10)
* transform type selector not available
* plots failing (see below for traceback)

```
15:17:48 - ERROR: SasView threw exception: x and y must have same first dimension, but have shapes (9073,) and (14251,)
Traceback (most recent call last):
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py", line 268, in finish_transform
    self._realplot.draw_real_space()
  File "/Users/pkienzle/Source/sasview/src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py", line 101, in draw_real_space
    self.axes.plot(data3.x, data3.y, label="3D Correlation")
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1527, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 406, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 383, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/Users/pkienzle/anaconda/envs/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 242, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (9073,) and (14251,)
```

**Comment by wpotrzebowski** [comment]
@pkienzle : "Help" button for correlation function should work and should be compatible with 5.0. It is apparently known issues with range bars and manual says: "These bars may be moved by entering appropriate values in the Q range input boxes."  
I've managed to reproduce missing name and failing transform but plotting seems to be working fine.

**Comment by wpotrzebowski** [comment]
The "transform" error is raised by this line https://github.com/SasView/sasview/blob/6b25ad8ddea9e140417d4b448e8c711e73271e83/src/sas/qtgui/Perspectives/Corfunc/CorfuncPerspective.py#L101 but most likely caused by some earlier calculations. Can @rprospero take a look on it, please?

**Comment by rprospero** [comment]
I can reproduce the plotting issues on Linux.

**Comment by rprospero** [comment]
* I cannot reproduce the name not appearing in the name box.

* I can confirm that the range bars are currently not dragable by design, though that's probably a worthwhile enhancement.  I'll add an issue for that.

* It should be possible to scroll the input dialog.  I'll work on that.

* The sigma value should not have changed.  That also bears investigation.

* The transform type selector was removed because the Hilbert transform has never been properly supported.  Adding this support is useful, but I'll make a new issue for it, since it's not a regression.

* The plotting issue should be handled by #1352.

**Comment by wpotrzebowski** [comment]
The issue with the non-appearing name has already been fixed: https://github.com/SasView/sasview/commit/9fcff7754972c335be79958348a4a4bed2885532

**Comment by rprospero** [comment]
The bar dragging issue will be handled by pr #1357.

**Comment by rprospero** [comment]
Scrolling the input dialog is now supported in pr #1352.

**Comment by butlerpd** [comment]
@rprospero, @wpotrzebowski , @pkienzle , @smk78 - It seems everything has a separate issue or has been fixed? Can this be closed now?
Temporarily assigning to 5.0.3

**Comment by smk78** [comment]
Yes, I think this ticket can be closed. #1352 and #1357 have been merged. The name of the data set still does not appear, and the input area still needs to be made scrollable  (this is using 5.0.2 on W10). I will create tickets for those.

**Comment by butlerpd** [comment]
Ok .. going to reassign to 4.3 then close.
