### ISSUE TITLE
Q Resolution Estimator does not generate a plot in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1422]
Testing 5.0.1RC on x64 in W10.

The Q Resolution Estimator tool in 5.0.1 does not generate a plot.

**Comment by rozyczko** [comment]
Fixed in ESS_GUI_5.0.1_fixes (will merge with ESS_GUI soon)

**Comment by smk78** [comment]
Tested in 5.0.1 Build 321 and locally-built from ESS_GUI branch. Still not working. Was this really merged into ESS_GUI?

**Comment by rozyczko** [comment]
Just checked with the current ESS_GUI. This is what I get. Should we expect something else?

![Untitled](https://user-images.githubusercontent.com/8266281/73747936-c241ae80-4758-11ea-8e57-06edfd004e32.png)

**Comment by smk78** [comment]
Testing locally-built ESS_GUI on W10/x64 this afternoon I get:

![image](https://user-images.githubusercontent.com/10938679/73868215-fd6add00-483f-11ea-83a5-65ce4263b0b2.png)

I also note that if you do not put spaces after the commas in the Qx/Qy boxes the box goes red and the Compute button is greyed out.

**Comment by butlerpd** [comment]
5.0.1 is out so we need to either move this to 5.0.2 or close it.

I checked this with the 5.0.1 release downloaded, installed and ran and got the same as @rozyczko. @smk78 are you sure you hit the compute button and that it was recognized? I note that when loading the tool, even though there are values in the boxes the graph is empty?

On another note, I am not exactly sure why this happens (must be something about the mismatch between the Q covered by the detector vs the Qs the resolution is requested?) but I originally didn't notice the 0.01 and input instead 0.1,0.2 etc.  The graph in this case moved the 0,0 to the bottom left corner instead of in the center.  Changing the Q values back to 0.01,0.02 etc the center moved back to the center and looks exactly as what @rozyczko shows.

Recommend this ticket be closed.

**Comment by smk78** [comment]
Just tested 5.0.1 release and I know also get the same as @rozyczko . The help doc needs some attention, but the functionality is there. Am closing this ticket.
