### ISSUE TITLE
5.1 gui initialisation issue for Onion model

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1453]
set up to do a fit with say sphere times hardsphere,
then change the P(Q) model to onion, which loads with default 1 layer,
then plot the sld profile, note it has 10 not 1 layers !

Then change S(Q) to "none", note now n actually changes to 10

Seems to only do this for Onion, not Core_multishell, and you have to have S(Q) chosen before changing the model to onion.

**Comment by rozyczko** [comment]
I am able to reproduce this - time to fix it then.

**Comment by rozyczko** [comment]
I can reproduce it and indeed it's slightly infuriating. I _think_ it has to do with numpy complaining about float->int conversion as in #1463 reported by Steve but need more investigation.

**Comment by pkienzle** [comment]
The numpy issue is addressed in PR SasView/sasmodels#382.

**Comment by RichardHeenan** [comment]
The bug is still there in the sasmodels pak branch https://github.com/SasView/sasmodels/pull/382

**Comment by butlerpd** [comment]
Before moving this ... @RichardHeenan did you not say this was fixed recently? if so we should just close the issue.

**Comment by butlerpd** [comment]
Never mind.  Have just tested the latest master build of ESS_GUI and the odd behavior still exists so the changes to sasmodels had no effect on this as far as I can tell.

Thus, as per today's conversation, am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release.

**Comment by butlerpd** [comment]
@RichardHeenan I think this is fixed and can now be closed? following the above recipe works perfectly now for me.  I will move to 5.0.4 for now but we should close it if it was fixed during hackathon?

**Comment by RichardHeenan** [comment]
The specific bug seems fixed also to me in 5.0.3, so closing this ticket.
