### ISSUE TITLE
Project load of Theory items causes the Fit panel to go blank

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1689]
The whole FitPage with no data is bit weird in that you can only (I think) do it first thing in a fresh sasview session.

In 5.0.3 release on Windows, I set up no data, sphere, smeared 15%, then tried save project, closed sasview, started again, load project comes up with an completely blank FitPage. needs investigation!

_Originally posted by @RichardHeenan in https://github.com/SasView/sasview/issues/1686#issuecomment-709252682_

**Comment by krzywon** [comment]
This might be a related to #1657 (though worded differently) which is already fixed in PR #1675.

**Comment by krzywon** [comment]
@rozyczko and @RichardHeenan I just tested this using main and think it is fixed. Could one or both of you test when you get a chance and either comment or close?

**Comment by RichardHeenan** [comment]
**In local Win10 build of Main, Calculated coreshellsphere with default Q range, (i.e. did not send any data to FitPage)
[theory_cssphere_smeared.json.txt](https://github.com/SasView/sasview/files/5879579/theory_cssphere_smeared.json.txt)**

Save project (file attached) gave 
10:35:14 - INFO: data cannot be serialized to json: <class 'PyQt5.QtWidgets.QLineEdit'>
10:35:14 - INFO: data cannot be serialized to json: <class 'method'>
10:35:14 - INFO: data cannot be serialized to json: <class 'PyQt5.QtWidgets.QLineEdit'>
10:35:14 - INFO: data cannot be serialized to json: <class 'method'>

**Start new session of sasview, load project gave only some title info in the M1 workspace and errors below. (The json seems to be missing the parameter values from the model? May be asking the impossible here to expect this to work???)**

10:36:05 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence

10:36:05 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence

10:36:05 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence

10:36:05 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence

QMdiArea::removeSubWindow: window is not inside workspace
QMdiArea::removeSubWindow: window is not inside workspace
QMdiArea::removeSubWindow: window is not inside workspace

**However, I have just gone back one step and tried saving a project with a normal fit, this is also giving errors, will edit this further later after investigation.**

**Comment by rozyczko** [comment]
seems like fallout from #1762?

**Comment by RichardHeenan** [comment]
**Yes loading a normal project (example attached)
[normal.json.txt](https://github.com/SasView/sasview/files/5879736/normal.json.txt)
 with a fit is giving me errors such as:**

11:06:51 - INFO: plugin model dir: C:\Users\rkh98\.sasview\plugin_models
11:06:51 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence

11:06:51 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence

11:06:51 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence

11:06:51 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence

QMdiArea::removeSubWindow: window is not inside workspace
QMdiArea::removeSubWindow: window is not inside workspace
QMdiArea::removeSubWindow: window is not inside workspace

**Comment by RichardHeenan** [comment]
Another project, with 3 data sets, changed Q ranges on FitPages 1 & 3, on loading fills 3 workspaces but only generated FitPage1 and 3, not 2, same errors. The plot for Fitpage3 has data legend M2

[threeset_changed_Qranges_in1and3.json.txt](https://github.com/SasView/sasview/files/5879984/threeset_changed_Qranges_in1and3.json.txt)


11:43:06 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence
11:43:06 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence
11:43:06 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
    q_min = min(self._calculator.x)
ValueError: min() arg is an empty sequence
11:43:06 - ERROR: Traceback (most recent call last):
  File "C:\sasview5\sasview\src\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
    q_max = max(self._calculator.x)
ValueError: max() arg is an empty sequence

**Comment by krzywon** [comment]
@rozyczko Possibly so. I'll look into this.

**Comment by krzywon** [comment]
I think the majority of the items for this ticket are fixed as of 5.0.4 RC4, with the exception of loading a project with fit tabs without data. The theory loading issue goes back to the original 5.0 release, so it might need it's own ticket.

**Comment by butlerpd** [comment]
@krzywon can you generate the appropriate new ticket and then close this one? Presumably these were fixed in 5.0.4 right?

**Comment by krzywon** [comment]
@smk78, what part or parts of this are still not working? From what I remember, when loading a theory fit with no data, it is loaded as a data set and is in the data loaded, but not in a fit page. Is my memory correct here?

**Comment by RichardHeenan** [comment]
In 5.0.4 I repeated my initial test - set up no data, sphere, smeared 15%, then tried save project, closed sasview, started again, load project comes up with an completely blank FitPage. 

The json file, attached,
[theory_cssphere_smeared2.json.txt](https://github.com/SasView/sasview/files/6465993/theory_cssphere_smeared2.json.txt)
 though it mentions the sphere model, does not have any parameter values stored inside it.

**Comment by RichardHeenan** [comment]
>From what I remember, when loading a theory fit with no data, it is loaded as a data set and is in the data loaded, but not in a fit page. Is my memory correct here?
Yes this is what is happening, so maybe this is what is expected? So perhaps this is a non-issue?

**Comment by RichardHeenan** [comment]
> **Yes loading a normal project (example attached) [normal.json.txt](https://github.com/SasView/sasview/files/5879736/normal.json.txt) with a fit is giving me errors such as:**

This project loads OK in 5.0.4 release

**Comment by RichardHeenan** [comment]
> Another project, with 3 data sets, changed Q ranges on FitPages 1 & 3, on loading fills 3 workspaces but only generated FitPage1 and 3, not 2, same errors. The plot for Fitpage3 has data legend M2. The reduced Q range on M1 is respected on FitPage1.
Also now loading OK in 5.0.4 release

**Comment by RichardHeenan** [comment]
So to conclude, I think this is all working apart from needing a discussion about what should happen if we save a project with only a theory. 
At present the json project has only the calculated I(Q), and the model name, but not any parameter values. On loading the data appears in the "data" tab, not the "theory" tab. 
is it worth the time & effort to go any further with this?

**Comment by krzywon** [comment]
Thanks for the detailed report, @RichardHeenan. I'll make a new ticket for theories loading as data and close this issue.

**Comment by smk78** [comment]
User HubertK posted to users@sasview.org:

>I'd like to use sasview to test several sets for a given theory (core-shell) 
>I can't seem to save each trial as a project
>When i save project and reopen, the model type and parameters have vanished

Testing with release 6.0.0, I created 3 FitPages (a sphere, a cylinder & an ellipsoid), and computed each to get the plots. I then saved the session as a project and closed down SasView. I then restarted SasView and opened the saved project. The computed theories are loaded but the FitPages are not recreated.

![image](https://github.com/user-attachments/assets/1ff05575-baaf-47b9-9f81-9d7e9a1517dd)

Looking at the thread above it seems that the original issue reported as long ago as 5.0.3 was never actually rectified.
