### ISSUE TITLE
Crash on opening documentation (Windows)

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#3367]
**Describe the bug**
Opening documentation leads to the application crashing without any message/error.
This is on Windows 10, hopefully only on my machine.

**To Reproduce**
1. Open SasView 6.1.0 a1 (from the installer)
2. Click on Help/Documentation
3. An empty widget shows up
4. Wait several seconds
5. SasView crashes

**Expected behavior**
Documentation should be generated and displayed on 1st run.

**Screenshots**

![Image](https://github.com/user-attachments/assets/07036385-8808-4284-b11b-dc6c840ed498)

**SasView version (please complete the following information):**
 - Version: 6.1.0a1

**Operating system (please complete the following information):**
 - OS:  Windows 10

**Additional context**

**Comment by krzywon** [comment]
@rozyczko - can you try the latest installer from #3326, please? I think this was already fixed by #3330.

**Comment by rozyczko** [comment]
The most recent installer from https://github.com/SasView/sasview/actions/runs/14892573527 still fails for me

**Comment by krzywon** [comment]
Can you look in `~/AppData/Local/` to see if there is a `sasview` directory and if there is, what is in it?

**Comment by rozyczko** [comment]
The location listed in the title bar of the doc window (as in the screenshot) is
`AppData/Local/sasview/SasView/6.1.0/doc/build/html/index.html`
The folder is where it is supposed to be, and clicking on `index.html` brings the main doc page in my default browser just fine.
Maybe it is the browser invocation from Python that is misbehaving?

**Comment by rozyczko** [comment]
The dev build works just fine, which makes this an interesting case to debug...
Does it work on your windows machine, @krzywon ?

**Comment by rozyczko** [comment]
6.1.0 a1 works fine on another windows box (Win11). It also works on a Win 10 VM.
This means there's something wrong with my development machine.
Demoting from `Blocker` then.

**Comment by llimeht** [comment]
Given sasview is quite good at capturing exceptions and logging them without crashing, does this imply that it's in Qt rather than in the Python code? 

- If you're able to run sasview.exe from inside a C debugger (like gdb, as opposed to a Python debugger like pdb), you might get some logs or a stack trace that gives more info.
- Running sasview.exe from a pwsh/cmd/bash terminal might also provide a little info as to what and where 

I assume sasview's own log file doesn't contain any clues?

**Comment by rozyczko** [comment]
No log entry is present for the crash, just the info on opening the SV instance.

I am not able to reproduce the crash on any other machine, so hopefully it's a fluke.
I'm closing this as non-reproducible, but this can be revisited if more cases pop up.
