### ISSUE TITLE
PrView now broken (Trac #381)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#515]
In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:

Discovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  

Used test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues

1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually. Error reported in sasview log is:

```text
2015-03-22 10:57:56,072 ERROR InversionControl._on_accept_alpha: String or Unicode type required
2015-03-22 10:58:40,540 ERROR InversionControl._on_accept_nterms: String or Unicode type required
```
2. The number of terms is NOT being evaluated.  Suggested value is always the defaule of 10.  Error reported in console is given below. In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.

```text
	Could not estimate number of terms
```  

3. The "explore box" is broken in windows but not on mac it seems.  
 a. You can put some numbers in but quickly some boxes become inaccessible such as "number of points" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  
 b. The alpha version on PC behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.

Migrated from http://trac.sasview.org/ticket/381
```json
{
    "status": "closed",
    "changetime": "2015-03-26T18:01:10",
    "_ts": "2015-03-26 18:01:10.330351+00:00",
    "description": "In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:\n\nDiscovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  \n\nUsed test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues\n\n1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually. Error reported in sasview log is:\n{{{\n2015-03-22 10:57:56,072 ERROR InversionControl._on_accept_alpha: String or Unicode type required\n2015-03-22 10:58:40,540 ERROR InversionControl._on_accept_nterms: String or Unicode type required\n}}}\n2. The number of terms is NOT being evaluated.  Suggested value is always the defaule of 10.  Error reported in console is given below. In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.\n{{{\n\tCould not estimate number of terms\n}}}  \n\n3. The \"explore box\" is broken in windows but not on mac it seems.  \n a. You can put some numbers in but quickly some boxes become inaccessible such as \"number of points\" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  \n b. The alpha version on PC behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-22T14:58:24",
    "component": "SasView",
    "summary": "PrView now broken",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 15:22:18`: **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 16:03:03`: **butler** changed description from:

> In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:
> 
> Discovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  
> 
> Used test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues
> 
> 1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually.
> 2. I don't think the number of terms is being evaluated correctly.  
>  a. It never seemed to go off of a suggested value of 10.  In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.  
>  b. Manually typing 24 works as well, while in the latest build if I type 21 or higher the box goes pink and refuses the number.  I vaguely remember a discussion that 20 should be a maximum ever needed but that would have been long long ago so not sure why it has changed now... and clearly for this very large monodisperse sphere it seems to do better with a larger number.
> 3. The "explore box" is broken.  
>  a. You can put some numbers in but quickly some boxes become inaccessible such as "number of points" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  
>  b. The alpha version behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.

to:

> In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:
> 
> Discovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  
> 
> Used test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues
> 
> 1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually. Error reported in sasview log is:
> {{{
> 2015-03-22 10:57:56,072 ERROR InversionControl._on_accept_alpha: String or Unicode type required
> 2015-03-22 10:58:40,540 ERROR InversionControl._on_accept_nterms: String or Unicode type required
> }}}
> 2. The number of terms is NOT being evaluated.  Suggested value is always the defaule of 10.  Error reported in console is given below. In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.
> {{{
> 	Could not estimate number of terms
> }}}  
> 
> 3. The "explore box" is broken.  
>  a. You can put some numbers in but quickly some boxes become inaccessible such as "number of points" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  
>  b. The alpha version behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:24:35`: **butler** changed description from:

> In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:
> 
> Discovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  
> 
> Used test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues
> 
> 1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually. Error reported in sasview log is:
> {{{
> 2015-03-22 10:57:56,072 ERROR InversionControl._on_accept_alpha: String or Unicode type required
> 2015-03-22 10:58:40,540 ERROR InversionControl._on_accept_nterms: String or Unicode type required
> }}}
> 2. The number of terms is NOT being evaluated.  Suggested value is always the defaule of 10.  Error reported in console is given below. In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.
> {{{
> 	Could not estimate number of terms
> }}}  
> 
> 3. The "explore box" is broken.  
>  a. You can put some numbers in but quickly some boxes become inaccessible such as "number of points" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  
>  b. The alpha version behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.

to:

> In all the cleanup !PrView which worked relatively well in version 3.1 alpha just before code camp, is now very broken:
> 
> Discovered as I was trying to add the Help button to this panel (have this and Invariant left to finish documentation redesign).  Have decided not to confuse the issue by adding that now and would like to see this fixed first.  
> 
> Used test data 1000A_sphere_dsm.xml for most all of my testing (NOTE: the DMAX is very large on this .. and in fact the name is WRONG it is 1000nm!!). Main issues
> 
> 1. Buttons do not update value (regularization constant and number of terms). It does seem to take the number typed in manually. Error reported in sasview log is:
> {{{
> 2015-03-22 10:57:56,072 ERROR InversionControl._on_accept_alpha: String or Unicode type required
> 2015-03-22 10:58:40,540 ERROR InversionControl._on_accept_nterms: String or Unicode type required
> }}}
> 2. The number of terms is NOT being evaluated.  Suggested value is always the defaule of 10.  Error reported in console is given below. In the alpha release, once I put in a Dmax of 20,000 (2 microns diameter) it suggests 25 and clicking on the button properly puts that value into the parameter box.
> {{{
> 	Could not estimate number of terms
> }}}  
> 
> 3. The "explore box" is broken in windows but not on mac it seems.  
>  a. You can put some numbers in but quickly some boxes become inaccessible such as "number of points" and may even get stuck in max or min and not allow chaning any other value ... including the drop down.  
>  b. The alpha version on PC behaves very well and even deals elegantly with putting a SMALLER number in the max by simply inverting the plot scale.

**Comment by mdoucet** [comment]
Trac update at `2015/03/23 13:04:15`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "accepted"

**Comment by mdoucet** [comment]
Trac update at `2015/03/23 18:08:07`: 
* **mathieu** changed _comment0 from "This should now be fixed. I believe #3 was caused by #1. It now works on OSX. Someone should test on Windows." to "1427134117105748"
* **mathieu** commented:

This should now be fixed. I believe item 3 was caused by item 1. It now works on OSX. Someone should test on Windows.


* **mathieu** changed owner from "mathieu" to "butler"
* **mathieu** changed status from "accepted" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/03/25 04:06:59`: 
* **butler** commented:

Nope ...still broken.  Now in fact clicking on "explore" fails altogether (no panel pops up).  the traceback yields

```text
Traceback (most recent call last):
  File "C:\Users\Paul\git\sasview\src\sas\perspectives\pr\inversion_panel.py", line 893, in _on_explore
    dialog = ExploreDialog(pr, 10, None, -1, "")
  File "C:\Users\Paul\git\sasview\src\sas\perspectives\pr\explore_dialog.py", line 182, in __init__
    self.__do_layout()
  File "C:\Users\Paul\git\sasview\src\sas\perspectives\pr\explore_dialog.py", line 336, in __do_layout
    self.output_box.SetEditable(False)
  File "C:\Users\Paul\workspace\SasView\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 13334, in SetEditable
    return _core_.TextEntryBase_SetEditable(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!HasFlag(wxCB_READONLY)" failed at ..\..\src\msw\combobox.cpp(421) in wxComboBox::GetEditHWND(): read-only combobox doesn't have any edit control
```

Note that this is on my development machine only as the Jenkins site is down so official builds are not being built.


* **butler** changed owner from "butler" to "mathieu"

**Comment by mdoucet** [comment]
Trac update at `2015/03/26 18:01:10`: 
* **mathieu** commented:

I'm closing this ticket and moving the part that was unrelated to the cleanup effort to a new ticket.
The item three above appears to be related to the move to wx 3.0. It has been moved to #531.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "assigned" to "closed"
